### ISSUE TITLE
FreeBSD 10 uses clang compiler, not g++

### ISSUE THREAD

**Issue by daoswald** [tsee/extutils-cppguess#1]
Refer to https://rt.cpan.org/Public/Bug/Display.html?id=92595

This issue was re-opened in the Inline::CPP RT queue when Inline::CPP shifted its compiler detection from internal logic to ExtUtils::CppGuess.

I'll have a look at this within the next day or so, and should be able to adapt the Inline::CPP-specific patch to EU::CG.

**Comment by mohawk2** [comment]
This is now in place in 0.13.
