### ISSUE TITLE
Test fails with ExtUtils-MakeMaker ≥ 7.05_05 present

### ISSUE THREAD

**Issue by mpan-pl** [tsee/extutils-cppguess#10]
If ExtUtils-MakeMaker 7.05_05 or newer is present (including 7.07), `make test` fails: https://gist.github.com/mpan-pl/5e850a276298ffbfaa12. If ExtUtils-MakeMaker is not present or version 7.05_04 or older is used (tested up to 7.04), ExtUtils-CppGuess test succeeds.

If this will help with tracking the source of the problem: the issue does not happen before commit 1c525d7424fa635b82d30a9035b5dc44b6ff2368.

Tested with Perl 5.22.

**Comment by ioquatix** [comment]
I also am having this problem, or something similar.

**Comment by ioquatix** [comment]
The solution for me was to uninstall makemaker:

     sudo pacman -R perl-extutils-makemaker-aur

Then the build proceeded correctly.

**Comment by mohawk2** [comment]
This was addressed with EUMM 7.14.

**Comment by ioquatix** [comment]
Still having this problem with 7.18

**Comment by mohawk2** [comment]
@ioquatix If this is still a problem, could you reopen? 0.13 provides a lot more reporting info that will help us nail this. Closing till then.

**Comment by ioquatix** [comment]
Okay. I have built it since then and it seemed to work okay.
