### ISSUE TITLE
Better docs and examples

### ISSUE THREAD

**Issue by wollmers** [tsee/extutils-cppguess#12]
Doing my first C++ CPAN distribution I had a hard way to do it portable across architectures.

IMHO better "real" examples of Makefile.PL would help.

Here is [mine](https://github.com/wollmers/Image-Seek) which at the moment passes all [tests](http://matrix.cpantesters.org/?dist=Image-Seek+0.04_02).

**Comment by mohawk2** [comment]
Could you help me understand what's not already in the docs? Your `Makefile.PL` just uses this module in one line, which suggests it's working great? Please reopen with your thoughts!
