### ISSUE TITLE
Should be testable by mocking %Config

### ISSUE THREAD

**Issue by daoswald** [tsee/extutils-cppguess#4]
This is being worked on in the "tests" branch:

We should be able to pass a mock %Config to the constructor so that it becomes easier to test logic for various platforms. In particular, 'osname', 'cc', 'osvers', 'gccvers' are probably relevant parts of the %Config hash.  Testability _is_ hampered to a degree by the logic that uses system calls, but at least being able to mock %Config as an official part of the UI is a step in the right direction.

**Comment by mohawk2** [comment]
This is now in place, with the EUMM approach. It is *also* possible to pass a `config` arg to `new`.
