### ISSUE TITLE
Support %ENV overriding default configurations

### ISSUE THREAD

**Issue by daoswald** [tsee/extutils-cppguess#6]
https://github.com/Perl-Toolchain-Gang/ExtUtils-CBuilder/blob/master/lib/ExtUtils/CBuilder/Base.pm#L40

In particular, ENV{CC}, ENV{CXX}, ENV{CFLAGS}, ENV{CXXFLAGS} ... LD, LDFLAGS

leont: CFLAGS may be problematic, and intends to open a ticket in CBuilder, so be sure to check back before proceeding too far.

---
# toolchain -- 8/19/14

[leont] There is a smoker that sets CFLAGS to something system related (I think he's using Gentoo), and then all ExtUtils::CBuilder builds fail
[leont] So I get regular black smoke for Module::Build from him :-/
[davido_] Is he misconfigured, or is cbuilder doing the wrong thing?
 Anyway, I'll try to check back in cbuilder to see how any issue you raise there plays out.
[leont] That is currently not well defined

**Comment by mohawk2** [comment]
Without more specifics, this is not possible to pursue. If @daoswald or @leont could provide more info, we can crack this. Forced to close until then.
